version: '3.8'

services:

  stardog:
    image: stardog/stardog
    platform: linux/amd64
    ports:
      - "5820:5820"
    volumes:
      - /Users/Kevin/Desktop/StardogHome/:/var/opt/stardog
    environment:
      STARDOG_SERVER_JAVA_ARGS: '-Xmx16g -Xms16g'